package com.conditionevaluator;

public enum TokenKind {
    SPECIALCHARACTER,
    STRING,
    BAREWORD,
    EQUAL,
    NOTEQUAL,
    AND,
    OR,
    ENDOFINPUT,
    CLOSEPARENTHESIS,
    OPENPARENTHESIS,
    FLOAT,
    GREATERTHAN,
    LESSTHAN,
    GREATERTHANANDEQUAL,
    LESSTHANANDEQUAL,
    INTEGER
}
